name: Run tests
on:
  pull_request:
    branches:
      - lef/**
  push:
    branches:
      - lef/**

jobs:
  test-all-solutions:
    name: Testing all solutions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate Python version
      run: python --version

    - name: Install dependencies
      run: make pip-install

    - name: Run tests
      run: make test
