name: Run tests
on:
  pull_request:
    branches:
      - lef/**
  push:
    branches:
      - lef/**

jobs:
  test-all-solutions:
    name: Testing all solutions
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate Python version
      run: python --version

    - name: Install dependencies
      run: make pip-install

    - name: Run tests
      run: make test

  another-job:
    name: Some other name
    needs: test-all-solutions
    runs-on: ubuntu-latest
    steps:
      - name: Hello world from another job
        run: echo "Hello world from another job"

  yet-another-job:
    name: Some other other job
    runs-on: ubuntu-latest
    steps:
      - name: Hello world from YET another job
        run: echo "Hello world from YET another job"
